name: kyo-web-agenda - Build and Deploy to main-build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Push to main-build
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main-build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build in Main Environment: ({sha}) {msg}"
